language: node_js
node_js:
  - "8.9"
before_install:
  - npm install -g yarn --cache-min 999999999
install:
  - yarn
script:
  - yarn
  - yarn production
  - zip -r ./compare-results-visualizer.0.1.${TRAVIS_BUILD_NUMBER}.zip ./images/* ./js/* ./index.html ./server.js
deploy:
  - provider: releases
  - api_key: ${GITHUB_API_KEY}
  - file: ./compare-results-visualizer.0.1.${TRAVIS_BUILD_NUMBER}.zip
  - skip_cleanup: true
